### ISSUE TITLE
Sometimes the screen is very faded

### ISSUE THREAD

**Issue by sperez91** [veebch/stonks#9]
Not sure if I have a bad unit. I've set the config file VCOM value to -2.14 as seen on the screenshot. Sometimes the screen has strong dark writing but most of the time it looks very faded. Seems to always happen when there's sun shining on it, not sure if there's a correlation. Let me know if you have any ideas. Thanks!
![2022-07-23 15_56_47-Photo in Cryptoticker - Google Photos](https://user-images.githubusercontent.com/5923672/180625516-939b5158-69a9-404b-8f0a-6fae3ab0fa0f.jpg)

**Comment by veebch** [comment]
I've seen a faded screen once, on the same model of screen but that was running other software. I assumed it was the software rather than the screen. I will google around and look at it (and email you in the meantime)

**Comment by sperez91** [comment]
At night or when windows are closed the screen looks fine. Unfortunately, the blacks now look more like dark grays but it's ok. I'm sure the sunlight is affecting it because I found some material on Waveshare's website talking about taking UV precautions if it's going to be exposed to the sun.

The only software my raspberry pi is running are the ones necessary for the stonks.py to run

**Comment by veebch** [comment]
I can confirm that the I've managed to reproduce the sunlight issue. If the screen refreshes while in sunlight, the resulting image is very faded, it seems to only be short term for me, but it has only been intermittently in direct sunlight.
